# Generated by Django 4.0.1 on 2022-01-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'car'), ('Motorcycle', 'motorcycle'), ('Motorhomes & Caravanas', 'motorhomes_or_caravanas'), ('Trucks', 'trucks')], max_length=50)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'petrol'), ('Diesel', 'diesel'), ('Electric', 'electric'), ('Other', 'other')], max_length=15)),
                ('transmission_type', models.CharField(choices=[('Automatic transmission', 'automatic'), ('Manual gearbox', 'manual'), ('Semi-automatic', 'semi-automatic')], max_length=40)),
                ('mileage', models.IntegerField(default=0)),
            ],
        ),
    ]
