# Generated by Django 4.0.1 on 2022-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('automatic', 'Automatic transmission'), ('manual_gearbox', 'Manual'), ('semi-automatic', 'Semi-automatic')], max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('motorhomes_or_caravanas', 'Motorhomes & Caravanas'), ('trucks', 'Trucks')], max_length=50),
        ),
    ]
