# Generated by Django 4.0.1 on 2022-01-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_price_car_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user_id',
            new_name='user',
        ),
    ]
