# Generated by Django 4.0.1 on 2022-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_user_id_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('Automatic', 'Automatic transmission'), ('Manual_gearbox', 'Manual'), ('Semi-automatic', 'Semi-automatic')], max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Motorhomes Or caravanas', 'Motorhomes & Caravanas'), ('Trucks', 'Trucks')], max_length=50),
        ),
    ]
