# Generated by Django 4.0.1 on 2022-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_end_rent',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='date_start_rent',
            field=models.DateField(null=True),
        ),
    ]
