# Generated by Django 4.0.1 on 2022-02-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_price_car_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_end_rent',
        ),
        migrations.RemoveField(
            model_name='car',
            name='date_start_rent',
        ),
    ]
