# Generated by Django 4.0.1 on 2022-02-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_car_date_end_rent_remove_car_date_start_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
    ]
