# Generated by Django 4.0.1 on 2022-01-30 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_date_end_rent_car_date_start_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_rent_car', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentCart',
            new_name='RentCar',
        ),
    ]
