# Generated by Django 4.0.1 on 2022-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rent_car', '0002_rename_rentcart_rentcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='date_end_rent',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='date_start_rent',
            field=models.DateField(null=True),
        ),
    ]
