# Generated by Django 4.0.1 on 2022-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_auth', '0002_alter_carsuser_managers_carsuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsuser',
            name='profile_photo',
            field=models.ImageField(default='static/images/default.jpg', upload_to='profile_photos'),
        ),
    ]
